spring:
  application:
    name: keycloak-admin
  datasource:
    driverClassName: org.postgresql.Driver
    username: @db-username@
    password: @db-password@
    url: @db-url@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate